### ISSUE TITLE
Vb Generated Classes Master Error

### ISSUE THREAD

**Issue by ripteqdavid** [MikeGriffinReborn/EntitySpaces#2]
Hi Mike,
I was very excited to see ES 2019 now available on GitHub.  I've just downloaded all the components to upgrade an existing 2012 ES application which was written in VB.

When I tried to generate the entities in ES Studio, the Custom entities were fine, however I get the following error for the Generated entities (note: I tried generating the entities in C# and got no errors for both Custom and Generated - this looks to be an issue with VB only).

```
Error Found in C:\Program Files (x86)\EntitySpaces 2019\CodeGeneration\Templates\EntitySpaces\VB\Generated\Generated - esEntity (VB).est on line 245
No overload for method 'EntityRelationName' takes 3 arguments

Error Found in C:\Program Files (x86)\EntitySpaces 2019\CodeGeneration\Templates\EntitySpaces\VB\Generated\Generated - esEntity (VB).est on line 303
No overload for method 'EntityRelationName' takes 3 arguments



   at EntitySpaces.CodeGenerator.Template.Execute(Root esMeta, String templateLocation)
   at EntitySpaces.AddIn.ucTemplates.OnExecute(TemplateDisplaySurface surface)
```

**Comment by MikeGriffinReborn** [comment]
Hmmmm. I've been doing this in my spare time and just hate to give you this answer, I've only been maintaining the C# side of things. There have been big changes on the C# side when it comes to improving and modernizing the syntax including the templates that generate the code. It could be that this winter (it's coming) I find the time to make it happen?

**Comment by ripteqdavid** [comment]
Not to worry too much Mike. I’ve been porting most code to C#, and you can also create mixed solutions now. 

I might just seperate the DAL into a new C# project within the solution.

Thanks for keeping ES alive!
