### ISSUE TITLE
Use cases for using EntitySpaces.

### ISSUE THREAD

**Issue by MNF** [MikeGriffinReborn/EntitySpaces#3]
EntitySpaces was a great tool in 2007-2008, when MS entity framework wasn’t available yet, and our legacy application still use it for a few tables. But when will you recommend to use it now? Is it only for upgrading old applications, that are using original ES? Or you suggest to use in in new applications as well?. Please add the answer to readme.md, as it will be interesting to all readers.
Btw, why did you create this repository under new name, not under EntitySpaces? It will be better to cross-link old and new EntitySpaces repositories.

**Comment by MikeGriffinReborn** [comment]
EntitySpaces as it us on here works just fine, it has some nice enhancements based on language improvements in C# too. However, my goal now is to remove a lot of the "weight" of it and by that I mean a ton of dead code, or old code that supported a lot of things that are no longer relevant. This would help me pair down the code generation piece which is the complex part at this point. I have some vacation time that I am taking and going to work on this over the holidays.

**Comment by trran** [comment]
I'm sorry, I do not know English:

Hi Mike, I've been working with EntitySpaces for a long time. We have even added validations to the entities, we have also added AfterSaved, BeforeSaved, among other things, I have always wanted to thank you for this framework, before I looked for how to communicate with you, but finding nothing, I thought you were dead, but good that not.

Thanks for EntitySpace.

**Comment by MikeGriffinReborn** [comment]
Ha, thanks Tran, not dead yet, still doing great.  EntitySpaces is probably going to be completely reborn by spring time in a much more lite framework and an even more fluent API ...

[Me and my Wife](https://scontent-ort2-1.xx.fbcdn.net/v/t1.0-9/59785477_2021982501443197_7100023102876155904_o.jpg?_nc_cat=103&_nc_ohc=6tvYQ4Px6yoAQnm8sYMjelwtC9olMR338sNgcs8kQpMjRC8FWtLh-zEVw&_nc_ht=scontent-ort2-1.xx&oh=edde37b8e9ba95f65a2c46b222eb7608&oe=5E7E952C)

**Comment by trran** [comment]
Thank you for answering, I will continue this transformation process with you, I hope to cooperate with EntitySpace even if it is testing. i feel my poor google english.

**Comment by MikeGriffinReborn** [comment]
I have added support for MySQL and SQLite and have greatly improved the API, if you look at the main page the documentation has all been updated, the API is streamlined and very complete.
