### ISSUE TITLE
Member names cannot be same as their enclosing type

### ISSUE THREAD

**Issue by alrosal** [MikeGriffinReborn/EntitySpaces#4]
Hi Mike,

First here are the versions I am using (not sure if some of them are related):
- EntitySpace Studio 2019.1.0828.0
- Visual Studio 2019
- .Net Core 3.0

I am generating from the C# template on the ES Studio 2019. After compiling I got this error:
![image](https://user-images.githubusercontent.com/5661583/70441914-3b61b400-1ad0-11ea-96ed-d83841d20bfb.png)

But not every entity gets this error.

**Comment by trran** [comment]
possibly you added the generated class to the custom or the custom to the Generated. in short you have two custom or two generated and not one custom and one generated

**Comment by MikeGriffinReborn** [comment]
Ya, it's the ForeignKey, if you notice the foreignKey is there in the #region name. You need to to give it an alias because it looks like you have a self referencing key and the property name AwardCategories is matching the class name. In the EntitySpaces Studio, on the Metadata Tab, drill into that table, then it's foreignKeys and give it an Alias and Save it (the little disk icon). Then regenerate it.

**Comment by MikeGriffinReborn** [comment]
I'll be putting out a new EntitySpaces studio that will tell you exactly what to Alias when that happens in the future. It will make it trivial to override

**Comment by alrosal** [comment]
> Ya, it's the ForeignKey, if you notice the foreignKey is there in the #region name. You need to to give it an alias because it looks like you have a self referencing key and the property name AwardCategories is matching the class name. In the EntitySpaces Studio, on the Metadata Tab, drill into that table, then it's foreignKeys and give it an Alias and Save it (the little disk icon). Then regenerate it.

This worked. Thanks!

**Comment by jmarq143** [comment]
Can someone please help! I came across this very same issue and I came across this post on here...  However, the fix thats mentioned here is not working for me. 
I tried going in to the metadata section -> then it's foreign Keys section and give it an Alias (Alias was already filled out there, but I changed it to something custom anyway) and Save it by clicking on the little disk icon there. Then I regenerated the generated code using the studio.. but it still created .  
However I am still getting the same error.
Could you please let me know if I'm doing anything wrong.
I am using Entity Space Studio version 2019.1.1218.0
Visual Studio 2017
.net framework 4.6.1
