### ISSUE TITLE
Where do I get the 1.5.x binaries as a nuget?

### ISSUE THREAD

**Issue by HeikoAdams** [MikeGriffinReborn/EntitySpaces#8]
Hi, are binaries (dll files) of version 1.5.x available as nuget?

**Comment by MikeGriffinReborn** [comment]
Hmmm, EntitySpaces was always on YEAR.MONTH.DAY versions so you'd always know how old a version you were on, thus the latest version of SQL is 2020.1.10 or January 10th, 2020. I suspect you were on one of the very early version of EntitySpaces. Are you trying to roll back to an older version of the original EntitySpaces?

**Comment by MikeGriffinReborn** [comment]
I will look on my laptop, those are from 2004 I think, I will see if I have them still

**Comment by HeikoAdams** [comment]
Thanks that would help me a lot because we've some self written libs which depend on that version and using a nuget would make it easier to keep them up2date until they have been ported to the current ES version.

**Comment by MikeGriffinReborn** [comment]
I didn't realize that you were actually wanting me to create a NuGet package for these? I thought maybe you had lost the DLL's and the installer was no longer available. Those assemblies are two old for me to package up and put on NuGet unfortunately, sorry.
