### ISSUE TITLE
Exception "incorrect syntax near 'TSEQUAL' when setting dbversion to 2012

### ISSUE THREAD

**Issue by HeikoAdams** [MikeGriffinReborn/EntitySpaces#9]
Hi, 
when using `DatabaseVersion = "2012"` as noticed in the project description saving data raises the exception from the title because in `Providers\EntitySpaces.SqlClientProvider\Shared.cs` the version check is only for `if (request.DatabaseVersion == "2005" || request.DatabaseVersion == "2008")` (line 360 and 490).

**Comment by MikeGriffinReborn** [comment]
Good catch, I'll fix that today. I'll turn the version into a number and then simply do a greater than. For now I guess you can temporarily set  your version to 2008 and it should work. Also, check out what's coming ...


[SQL "Over" methods and "out var" support for aliased columns](https://github.com/MikeGriffinReborn/EntitySpaces/wiki)

**Comment by MikeGriffinReborn** [comment]
This has been fixed in the SqlServer provider, 2020.2.1.0 which was just pushed, also, it supports the new OVER syntax, see the home page for OVER examples
